/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.manageAirliners;

import Business.Airliner;
import Business.Airplane;
import Business.Fleet;
import static UserInterface.manageCustomer.bookFlights.isInt;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author yiyangyang
 */
public class newAirplaneJPanel extends javax.swing.JPanel {

    /**
     * Creates new form newAirplaneJPanel
     */
 private JPanel CardSequenceJPanel;
 
 private Airliner airliner;
 ButtonGroup group = new ButtonGroup();
 ButtonGroup group1 = new ButtonGroup();
    newAirplaneJPanel(JPanel CardSequenceJPanel,Airliner airliner) {
        initComponents();   
        this.CardSequenceJPanel = CardSequenceJPanel;
        this.airliner = airliner;
      
        group.add(AvailableRadioButton);
        group.add(NAvailableRadioButton);
        AvailableRadioButton.setSelected(true);
        group1.add(ExpiredRadioButton);
        group1.add(NExpiredRadioButton);
        ExpiredRadioButton.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        yearTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AvailableRadioButton = new javax.swing.JRadioButton();
        NAvailableRadioButton = new javax.swing.JRadioButton();
        modelNumTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        serialNumTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        manuTxt = new javax.swing.JTextField();
        airportTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ExpiredRadioButton = new javax.swing.JRadioButton();
        NExpiredRadioButton = new javax.swing.JRadioButton();
        createBtn = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Create new Airplane ");

        jLabel3.setText(" Manufactured Year :");

        jLabel2.setText("Status:");

        AvailableRadioButton.setText("Available");

        NAvailableRadioButton.setText("Not available");

        jLabel4.setText("Model Number:");

        jLabel5.setText("Serial Number:");

        jLabel7.setText("Manufacturer:");

        jLabel8.setText("Airport:");

        jLabel10.setText(" Maintenance Certificate Status:");

        ExpiredRadioButton.setText("Expired");

        NExpiredRadioButton.setText("Not Expired");

        createBtn.setText("Create");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });

        btnBack.setText("<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(AvailableRadioButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(NAvailableRadioButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ExpiredRadioButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(NExpiredRadioButton))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(yearTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(91, 91, 91)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addGap(18, 18, 18)
                                            .addComponent(modelNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addGap(18, 18, 18)
                                            .addComponent(serialNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel8)
                                                .addComponent(jLabel7))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(airportTxt)
                                                .addComponent(manuTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(325, 325, 325)
                        .addComponent(createBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(btnBack)
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(modelNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(serialNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(manuTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(airportTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(ExpiredRadioButton)
                    .addComponent(NExpiredRadioButton))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(AvailableRadioButton)
                    .addComponent(NAvailableRadioButton))
                .addGap(22, 22, 22)
                .addComponent(createBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
        if("".equals(modelNumTxt.getText())||"".equals(serialNumTxt.getText())||"".equals(yearTxt.getText())||"".equals(manuTxt.getText())||"".equals(airportTxt.getText())){
            JOptionPane.showMessageDialog(null,"Please complete all fileds to create!");
        }
        else{
        if(isInt(modelNumTxt.getText())&&isInt(serialNumTxt.getText())&&isInt(yearTxt.getText())){
            int modelNum = Integer.parseInt(modelNumTxt.getText());
            int serialNum = Integer.parseInt(serialNumTxt.getText());
            int year = Integer.parseInt(yearTxt.getText());
            
            String manufacturer = manuTxt.getText();
            String airport = airportTxt.getText();
            
            String status = "";
            String certificate = "";
            Boolean isClick = true;
            if (AvailableRadioButton.isSelected() == isClick)
            {
                status = AvailableRadioButton.getText();
            }
            else if(NAvailableRadioButton.isSelected()== isClick)
            {
                status = NAvailableRadioButton.getText();
            }

            if (ExpiredRadioButton.isSelected() == isClick)
            {
                certificate = ExpiredRadioButton.getText();
            }
            else if(NAvailableRadioButton.isSelected()== isClick)
            {
                certificate = NExpiredRadioButton.getText();
            }

            Airplane v = airliner.getFleet().addAirplane();
            v.setStatus(status);
            v.setCertificate(certificate);
            v.setModelNum(modelNum);
            v.setSerialNum(serialNum);
            v.setAirport(airport);
            v.setAirLinerstart(airliner.getNameOfcompany());
            v.setManufacturer(manufacturer);
            v.setSeats(150);
            v.setYear(year);
            JOptionPane.showMessageDialog(null,"Airplane added successfully");

            modelNumTxt.setText("");
            serialNumTxt.setText("");
            
            airportTxt.setText("");
            manuTxt.setText("");
            yearTxt.setText("");
            AvailableRadioButton.setSelected(true);
            ExpiredRadioButton.setSelected(true);}

        else{JOptionPane.showMessageDialog(null,"Please input only numbers in field of Year, Serial Number, Model Number and Number of seats.");}
        
        }
    }//GEN-LAST:event_createBtnActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardSequenceJPanel.remove(this);
        Component[] componentArray = CardSequenceJPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        manageAirplanesJPanel manageAirplanesJPanel = (manageAirplanesJPanel) component;
        manageAirplanesJPanel.populateAirplaneTable();
        CardLayout layout = (CardLayout) CardSequenceJPanel.getLayout();
        layout.previous(CardSequenceJPanel);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AvailableRadioButton;
    private javax.swing.JRadioButton ExpiredRadioButton;
    private javax.swing.JRadioButton NAvailableRadioButton;
    private javax.swing.JRadioButton NExpiredRadioButton;
    private javax.swing.JTextField airportTxt;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton createBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField manuTxt;
    private javax.swing.JTextField modelNumTxt;
    private javax.swing.JTextField serialNumTxt;
    private javax.swing.JTextField yearTxt;
    // End of variables declaration//GEN-END:variables
}
