/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.manageCustomer;

import Business.Airliner;
import Business.CustomerDirectory;
import Business.Flight;
import Business.MasterScheduel;
import UserInterface.manageAirliners.ViewAirlinerJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yiyangyang
 */
public class searchBestFlights extends javax.swing.JPanel {

    /**
     * Creates new form searchBestFlights
     */
    private JPanel CardSequenceJPanel;
    private MasterScheduel masterScheduel;
    private CustomerDirectory cd;
    
    

    public searchBestFlights(JPanel CardSequenceJPanel, MasterScheduel masterScheduel, CustomerDirectory cd) {
        initComponents();    
        this.CardSequenceJPanel = CardSequenceJPanel;
        this.masterScheduel = masterScheduel;
        this.cd = cd;
    }
    
 private void populateTable(String departure,String destination,String preferedDay){
        DefaultTableModel dtm=(DefaultTableModel)bestFlightstbl.getModel();
        dtm.setRowCount(0);

        for(int i=0;i< masterScheduel.getMasterScheduel().size();i++){
            for(int k=0;k< masterScheduel.getMasterScheduel().get(i).getFlightSchedule().size();k++){
              
                Flight flight = masterScheduel.getMasterScheduel().get(i).getFlightSchedule().get(k);
                 if((departure.equals(flight.getDeparture()))&&destination.equals(flight.getDestination())&&preferedDay.equals(flight.getPreferedDay())){
                    Object[] row =new Object[6];
                    row[0]=flight;
                    row[1]=flight.getDate();
                    row[2]=flight.getPreferedDay();
                    row[3]=flight.getDeparture();
                    row[4]=flight.getDestination();
                    row[5]=flight.getAirliner().getNameOfcompany();
                    dtm.addRow(row);
                }
                 
            }
            
        }
         
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        destinationTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        departureTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bestFlightstbl = new javax.swing.JTable();
        bookBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        preferedDayBox = new javax.swing.JComboBox<>();
        viewCusBtn = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("Search Best Flights");

        jLabel3.setText("To:");

        jLabel2.setText("From:");

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        bestFlightstbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight ID", "Date", "Place of departure", "Destination"
            }
        ));
        jScrollPane1.setViewportView(bestFlightstbl);

        bookBtn.setText("Book");
        bookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookBtnActionPerformed(evt);
            }
        });

        jLabel4.setText("Prefered day:");

        preferedDayBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "day time", "morning", "evening" }));

        viewCusBtn.setText("View all customer");
        viewCusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCusBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(departureTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(destinationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(preferedDayBox, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(viewCusBtn)
                        .addGap(18, 18, 18)
                        .addComponent(bookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(departureTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destinationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(preferedDayBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewCusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if("".equals(departureTxt.getText()) || "".equals(destinationTxt.getText())){
            JOptionPane.showMessageDialog(null,"Please input flight information to search","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else{

        populateTable(departureTxt.getText(),destinationTxt.getText(),preferedDayBox.getItemAt(preferedDayBox.getSelectedIndex()));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookBtnActionPerformed
        // TODO add your handlstbling code here:
        int selectedRow=bestFlightstbl.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null,"Please select a row from table first to book","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else{
            Flight flight=(Flight)bestFlightstbl.getValueAt(selectedRow, 0);
            bookFlights panel =new bookFlights(CardSequenceJPanel,flight,cd);
            CardSequenceJPanel.add("bookFlightsJpanel",panel);
            CardLayout layout=(CardLayout)CardSequenceJPanel.getLayout();
            layout.next(CardSequenceJPanel);
        }                                       
    }//GEN-LAST:event_bookBtnActionPerformed

    private void viewCusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCusBtnActionPerformed
        // TODO add your handling code here:
        
        viewAllcusJPanel panel =new viewAllcusJPanel(CardSequenceJPanel,cd);
        CardSequenceJPanel.add("viewAllcusJPanel",panel);
        CardLayout layout=(CardLayout)CardSequenceJPanel.getLayout();
        layout.next(CardSequenceJPanel);
    }//GEN-LAST:event_viewCusBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bestFlightstbl;
    private javax.swing.JButton bookBtn;
    private javax.swing.JTextField departureTxt;
    private javax.swing.JTextField destinationTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> preferedDayBox;
    private javax.swing.JButton viewCusBtn;
    // End of variables declaration//GEN-END:variables
}
