/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Airplane;
import Business.AirplaneHistory;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import java.awt.List;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yiyangyang
 */
public class SearchJpanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchJpanel
     */
        private AirplaneHistory ah;
     SearchJpanel(AirplaneHistory ah) {
        initComponents();
        this.ah = ah;
       
    }
        public void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel)BairplaneTable.getModel();
        dtm.setRowCount(0); 
        
        for(Airplane vs: ah.getAirplaneHistory())
           
        {
            if("Boeing".equals(vs.getManufacturer())){
                
            Object row[] = new Object[8];
            
            row[0] = vs.getSerialNum();
            row[1] = vs.getModelNum();
            row[2] = vs.getAirLinerstart() + "\t to \t" + vs.getAirLinerend();
            row[3] = vs.getAirport();
            row[4] = vs;
            row[5] = vs.getSeats(); 
            row[6] = vs.getYear();
            row[7] = vs.getStatus();
            
            dtm.addRow(row);}
        }
    }
        
        
       
        
//        public void populateTable2(Airplane vs){
//        DefaultTableModel dtm = (DefaultTableModel)seatsTable.getModel();
//        dtm.setRowCount(0); 
//
//            Object row[] = new Object[8];
//            
//            row[0] = vs.getSerialNum();
//            row[1] = vs.getModelNum();
//            row[2] = vs.getAirLiner();
//            row[3] = vs.getAirport();
//            row[4] = vs;
//            row[5] = vs.getSeats(); 
//            row[6] = vs.getYear();
//            row[7] = vs.getStatus();
//            
//            dtm.addRow(row);
//        
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        jTabbedPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        Find1jPanel63 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        AvaiNumTxt7 = new javax.swing.JTextField();
        FindfBtn = new javax.swing.JButton();
        AnumBtn = new javax.swing.JButton();
        yearTxt = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        modelNumTxt = new javax.swing.JTextField();
        serialNumTxt = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        seatsNumTxt = new javax.swing.JTextField();
        manuTxt = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        airportTxt = new javax.swing.JTextField();
        airlinerTxt = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        airlinerendTxt1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        BairplaneTable = new javax.swing.JTable();
        jLabel41 = new javax.swing.JLabel();
        SearchBtn3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tab3yeartxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        searchBtn4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        yearTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        searchBtn5 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        seatsTable = new javax.swing.JTable();
        seatsYtxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        SeatsXtxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        yearTxt1 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        modelNumTxt1 = new javax.swing.JTextField();
        serialNumTxt1 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        seatsNumTxt1 = new javax.swing.JTextField();
        airportTxt1 = new javax.swing.JTextField();
        manuTxt1 = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        statusTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        iSNumTxt = new javax.swing.JTextField();
        Searchtab5Btn = new javax.swing.JButton();
        jLabel49 = new javax.swing.JLabel();
        certificateTxt = new javax.swing.JTextField();
        airlinerTxt1 = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        iModelNumTxt = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Searchtab6Btn = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        modelNumTable = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Searchtab7Btn = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        manuTable = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        airlinerstartTxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        airlinerendTxt = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        updateTimeBtn = new javax.swing.JButton();
        timeTxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        iAirportTxt = new javax.swing.JTextField();
        searchBtn6 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        airportTable = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel54 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel57 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        certificateTable = new javax.swing.JTable();
        expiredBtn = new javax.swing.JButton();

        jLabel14.setText("Last update time :");

        jLabel29.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel29.setText("Find  Airplane");

        jLabel30.setText("The First Available Airplane");

        jLabel31.setText("The number of Available Airplane:");

        FindfBtn.setText("Search");
        FindfBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindfBtnActionPerformed(evt);
            }
        });

        AnumBtn.setText("Search");
        AnumBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnumBtnActionPerformed(evt);
            }
        });

        yearTxt.setEditable(false);
        yearTxt.setDoubleBuffered(true);

        jLabel33.setText(" Manufactured Year :");

        jLabel34.setText("Model Number:");

        modelNumTxt.setEditable(false);
        modelNumTxt.setDoubleBuffered(true);

        serialNumTxt.setEditable(false);
        serialNumTxt.setDoubleBuffered(true);

        jLabel35.setText("Serial Number:");

        jLabel36.setText("Number of Seats:");

        seatsNumTxt.setEditable(false);
        seatsNumTxt.setDoubleBuffered(true);

        manuTxt.setEditable(false);
        manuTxt.setDoubleBuffered(true);

        jLabel37.setText("Manufacturer:");

        jLabel38.setText("Airport:");

        airportTxt.setEditable(false);
        airportTxt.setDoubleBuffered(true);

        airlinerTxt.setEditable(false);
        airlinerTxt.setDoubleBuffered(true);

        jLabel39.setText("Airliner:");

        airlinerendTxt1.setEditable(false);
        airlinerendTxt1.setDoubleBuffered(true);

        jLabel9.setText("to");

        javax.swing.GroupLayout Find1jPanel63Layout = new javax.swing.GroupLayout(Find1jPanel63);
        Find1jPanel63.setLayout(Find1jPanel63Layout);
        Find1jPanel63Layout.setHorizontalGroup(
            Find1jPanel63Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Find1jPanel63Layout.createSequentialGroup()
                .addGroup(Find1jPanel63Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Find1jPanel63Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AnumBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AvaiNumTxt7, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Find1jPanel63Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(Find1jPanel63Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Find1jPanel63Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel38)
                                .addComponent(jLabel39))
                            .addComponent(jLabel37)
                            .addComponent(jLabel36)
                            .addComponent(jLabel35)
                            .addComponent(jLabel34)
                            .addComponent(jLabel33))
                        .addGap(54, 54, 54)
                        .addGroup(Find1jPanel63Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Find1jPanel63Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(modelNumTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                .addComponent(yearTxt)
                                .addComponent(serialNumTxt)
                                .addComponent(seatsNumTxt)
                                .addComponent(manuTxt)
                                .addComponent(airportTxt))
                            .addGroup(Find1jPanel63Layout.createSequentialGroup()
                                .addComponent(airlinerTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(airlinerendTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(Find1jPanel63Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addGroup(Find1jPanel63Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel30)
                            .addComponent(jLabel29))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FindfBtn)))
                .addGap(0, 246, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Find1jPanel63Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
        );
        Find1jPanel63Layout.setVerticalGroup(
            Find1jPanel63Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Find1jPanel63Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel29)
                .addGap(24, 24, 24)
                .addGroup(Find1jPanel63Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FindfBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Find1jPanel63Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Find1jPanel63Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(modelNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Find1jPanel63Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(serialNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Find1jPanel63Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(seatsNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Find1jPanel63Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(manuTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Find1jPanel63Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(airportTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Find1jPanel63Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(airlinerTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(airlinerendTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(33, 33, 33)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Find1jPanel63Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(AvaiNumTxt7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AnumBtn))
                .addGap(0, 39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 804, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(76, Short.MAX_VALUE)
                    .addComponent(Find1jPanel63, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Find1jPanel63, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabbedPane.addTab("tab1", jPanel1);

        BairplaneTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial Number", "Model Number", "Airliner", "Airport", "Manufacturer", "Seats", "Year", "Status"
            }
        ));
        jScrollPane2.setViewportView(BairplaneTable);

        jLabel41.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel41.setText("Find the airplanes that are made by Boeing ");
        jLabel41.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        SearchBtn3.setText("Search");
        SearchBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtn3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 784, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel41, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(SearchBtn3)
                        .addGap(174, 174, 174)))
                .addGap(214, 214, 214))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel41)
                .addGap(13, 13, 13)
                .addComponent(SearchBtn3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("tab2", jPanel2);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Find all airplanes that were manufactured in a given year");

        tab3yeartxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tab3yeartxtActionPerformed(evt);
            }
        });

        jLabel2.setText("Please input year:");

        searchBtn4.setText("Search");
        searchBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtn4ActionPerformed(evt);
            }
        });

        yearTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial Number", "Model Number", "Airliner", "Airport", "Manufacturer", "Seats", "Year", "Status"
            }
        ));
        jScrollPane3.setViewportView(yearTable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(tab3yeartxt, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(searchBtn4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tab3yeartxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(searchBtn4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane.addTab("tab3", jPanel3);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel3.setText("Find an available airplane with seats between(x<=seats< y )");

        searchBtn5.setText("Search");
        searchBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtn5ActionPerformed(evt);
            }
        });

        seatsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial Number", "Model Number", "Airliner", "Airport", "Manufacturer", "Seats", "Year", "Status"
            }
        ));
        jScrollPane4.setViewportView(seatsTable);

        seatsYtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatsYtxtActionPerformed(evt);
            }
        });

        jLabel5.setText("Please input Y:");

        SeatsXtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeatsXtxtActionPerformed(evt);
            }
        });

        jLabel6.setText("Please input X:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SeatsXtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel6)))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(seatsYtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(searchBtn5))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(113, 113, 113))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel3)
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SeatsXtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatsYtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn5))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("tab4", jPanel4);

        jLabel40.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel40.setText("Find Exact Airplane by Serial Number");

        yearTxt1.setEditable(false);
        yearTxt1.setDoubleBuffered(true);

        jLabel42.setText(" Manufactured Year :");

        jLabel43.setText("Model Number:");

        modelNumTxt1.setEditable(false);
        modelNumTxt1.setDoubleBuffered(true);

        serialNumTxt1.setEditable(false);
        serialNumTxt1.setDoubleBuffered(true);

        jLabel44.setText("Serial Number:");

        jLabel45.setText("Number of Seats:");

        seatsNumTxt1.setEditable(false);
        seatsNumTxt1.setDoubleBuffered(true);

        airportTxt1.setEditable(false);
        airportTxt1.setDoubleBuffered(true);

        manuTxt1.setEditable(false);
        manuTxt1.setDoubleBuffered(true);

        jLabel46.setText("Manufacturer:");

        jLabel47.setText("Airport:");

        jLabel48.setText("Status:");

        statusTxt.setEditable(false);
        statusTxt.setDoubleBuffered(true);

        jLabel4.setText("Please input serial number:");

        Searchtab5Btn.setText("Search");
        Searchtab5Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Searchtab5BtnActionPerformed(evt);
            }
        });

        jLabel49.setText("Certificate:");

        certificateTxt.setEditable(false);
        certificateTxt.setDoubleBuffered(true);

        airlinerTxt1.setEditable(false);
        airlinerTxt1.setDoubleBuffered(true);

        jLabel50.setText("Airliner:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(iSNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(Searchtab5Btn))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel50)
                                .addGap(54, 54, 54)
                                .addComponent(airlinerTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel49)
                                        .addComponent(jLabel48, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jLabel46)
                                    .addComponent(jLabel45)
                                    .addComponent(jLabel44)
                                    .addComponent(jLabel43)
                                    .addComponent(jLabel42)
                                    .addComponent(jLabel47))
                                .addGap(54, 54, 54)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(modelNumTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(yearTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(serialNumTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(seatsNumTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(manuTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(airportTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(statusTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(certificateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(219, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel40)
                .addGap(250, 250, 250))
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel40)
                .addGap(36, 36, 36)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(iSNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Searchtab5Btn))
                .addGap(23, 23, 23)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(modelNumTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(serialNumTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(seatsNumTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(manuTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47)
                    .addComponent(airportTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel48)
                    .addComponent(statusTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(certificateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel49))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(airlinerTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel50))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("tab5", jPanel5);

        jLabel51.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel51.setText("Find Airplanes by Model Number");

        jLabel7.setText("Please input model number:");

        Searchtab6Btn.setText("Search");
        Searchtab6Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Searchtab6BtnActionPerformed(evt);
            }
        });

        modelNumTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial Number", "Model Number", "Airliner", "Airport", "Manufacturer", "Seats", "Year", "Status"
            }
        ));
        jScrollPane5.setViewportView(modelNumTable);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(iModelNumTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(Searchtab6Btn)
                .addGap(115, 115, 115))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(jLabel51)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel51)
                .addGap(42, 42, 42)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Searchtab6Btn)
                    .addComponent(jLabel7)
                    .addComponent(iModelNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        jTabbedPane.addTab("tab6", jPanel6);

        jLabel52.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel52.setText("Find all Manufacturer used by specific airliner");

        jLabel8.setText("Please input Airliner:");

        Searchtab7Btn.setText("Search");
        Searchtab7Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Searchtab7BtnActionPerformed(evt);
            }
        });

        manuTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Manufacturer", "Serial Number"
            }
        ));
        jScrollPane6.setViewportView(manuTable);

        jLabel11.setText("From");

        jLabel12.setText("to");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel52))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel8)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(airlinerstartTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(airlinerendTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Searchtab7Btn))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(115, 198, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel52)
                .addGap(28, 28, 28)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(airlinerstartTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(airlinerendTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Searchtab7Btn))
                .addGap(45, 45, 45)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("tab7", jPanel7);

        updateTimeBtn.setText("Show last Update time");
        updateTimeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateTimeBtnActionPerformed(evt);
            }
        });

        jLabel10.setText("Last update time :");

        jLabel53.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel53.setText("Find last update time of the fleet of airlines");

        jLabel13.setText("Please input airport:");

        iAirportTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iAirportTxtActionPerformed(evt);
            }
        });

        searchBtn6.setText("Search");
        searchBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtn6ActionPerformed(evt);
            }
        });

        airportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial Number", "Model Number", "Airliner", "Airport", "Manufacturer", "Seats", "Year", "Status"
            }
        ));
        jScrollPane7.setViewportView(airportTable);

        jLabel54.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel54.setText("Find airplanes by airport");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(194, 194, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(iAirportTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchBtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(309, 309, 309))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(updateTimeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 856, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabel53))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(jLabel54)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel53)
                .addGap(36, 36, 36)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateTimeBtn)
                    .addComponent(timeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel54)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iAirportTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(searchBtn6))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        jTabbedPane.addTab("tab8", jPanel8);

        jLabel57.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel57.setText("Find all airplanes that have expired maintenance certificate. ");

        certificateTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial Number", "Model Number", "Airliner", "Airport", "Manufacturer", "Seats", "Year", "Status"
            }
        ));
        jScrollPane8.setViewportView(certificateTable);

        expiredBtn.setText("Search");
        expiredBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expiredBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel57))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(expiredBtn)))
                .addContainerGap(122, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel57)
                .addGap(38, 38, 38)
                .addComponent(expiredBtn)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("tab9", jPanel10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Searchtab5BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Searchtab5BtnActionPerformed
        // TODO add your handling code here:
            boolean isValidInteger = true;
            int i = 0;
            int size = ah.getAirplaneHistory().size();
            if(isInt(iSNumTxt.getText())== isValidInteger){
                for(Airplane vs: ah.getAirplaneHistory())
                {
                    if(vs.getSerialNum() == Integer.parseInt(iSNumTxt.getText()))
                    {
                        yearTxt1.setText(String.valueOf(vs.getYear()));
                        modelNumTxt1.setText(String.valueOf(vs.getModelNum()));
                        serialNumTxt1.setText(String.valueOf(vs.getSerialNum()));
                        manuTxt1.setText(vs.getManufacturer());
                        seatsNumTxt1.setText(String.valueOf(vs.getSeats()));
                        airportTxt1.setText(vs.getAirport());
                        airlinerTxt1.setText(vs.getAirLinerstart() +"to" + vs.getAirLinerstart());
                        statusTxt.setText(vs.getStatus());
                        certificateTxt.setText(vs.getCertificate());
                        break;
                        }
                    else {
                        i++;
                        }
                    }
                while(size == i){
                        JOptionPane.showMessageDialog(null,"No matches airplane");
                        break;
                }
            }
            
            else
            {
                JOptionPane.showMessageDialog(null,"Please input numbers only");
            }
        modelNumTxt1.setText("");
        serialNumTxt1.setText("");
        seatsNumTxt1.setText("");
        airportTxt1.setText("");
        airlinerTxt1.setText("");
        manuTxt1.setText("");
        yearTxt.setText("");
        statusTxt.setText("");
        certificateTxt.setText("");
        
    }//GEN-LAST:event_Searchtab5BtnActionPerformed

    private void SeatsXtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeatsXtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeatsXtxtActionPerformed

    private void seatsYtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatsYtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatsYtxtActionPerformed

    private void searchBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtn5ActionPerformed
        // TODO add your handling code here:
        boolean isSeats = true;
        if(isInt(SeatsXtxt.getText()) == isSeats && isInt(seatsYtxt.getText())){
            int Minseats = Integer.parseInt(SeatsXtxt.getText());
            int Maxseats = Integer.parseInt(seatsYtxt.getText());

            if(!ah.getAirplaneHistory().isEmpty())
            {
                populateTable2(Minseats,Maxseats);
            }
       
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Please input numbers only");
        }
    }//GEN-LAST:event_searchBtn5ActionPerformed

    private void searchBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtn4ActionPerformed
        // TODO add your handling code here:

        if(!ah.getAirplaneHistory().isEmpty()){
            populateTable1();
        }
        else
        {
            JOptionPane.showMessageDialog(null,"No matches airplane now");
        }

    }//GEN-LAST:event_searchBtn4ActionPerformed

    private void tab3yeartxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tab3yeartxtActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_tab3yeartxtActionPerformed

    private void SearchBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtn3ActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_SearchBtn3ActionPerformed

    private void AnumBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnumBtnActionPerformed
        // TODO add your handling code here:
        int i = 0;
        if(!ah.getAirplaneHistory().isEmpty())
        {
            for(Airplane vs: ah.getAirplaneHistory())
            {
                if("Available".equals(String.valueOf(vs.getStatus()))){
                    i++;
                }
            }
            AvaiNumTxt7.setText(String.valueOf(i));
        }      
        else
        {
            JOptionPane.showMessageDialog(null,"No available airplane now");
        }
        
         
        
    }//GEN-LAST:event_AnumBtnActionPerformed

    private void FindfBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindfBtnActionPerformed
        // TODO add your handling code here:
        
        
        if(!ah.getAirplaneHistory().isEmpty())
        {
            for(Airplane vs: ah.getAirplaneHistory())
            {
                if("Available".equals(String.valueOf(vs.getStatus()))){
                    yearTxt.setText(String.valueOf(vs.getYear()));
                    modelNumTxt.setText(String.valueOf(vs.getModelNum()));
                    serialNumTxt.setText(String.valueOf(vs.getSerialNum()));
                    manuTxt.setText(String.valueOf(vs.getManufacturer()));
                    seatsNumTxt.setText(String.valueOf(vs.getSeats()));
                    airportTxt.setText(String.valueOf(vs.getAirport()));
                    airlinerTxt.setText(String.valueOf(vs.getAirLinerstart()));
                    airlinerendTxt1.setText(String.valueOf(vs.getAirLinerend()));
                    break;
                }

            }
        }
        else
        {
            JOptionPane.showMessageDialog(null,"No available airplane now");
        }
    }//GEN-LAST:event_FindfBtnActionPerformed

    private void Searchtab6BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Searchtab6BtnActionPerformed
        // TODO add your handling code here:
        boolean isSenum = true;
        if(isInt(iModelNumTxt.getText()) == isSenum ){
            
            if(!ah.getAirplaneHistory().isEmpty())
            {
                populateTable3();
            }

        }
        else
        {
            JOptionPane.showMessageDialog(null,"Please input numbers only");
        }
    }//GEN-LAST:event_Searchtab6BtnActionPerformed

    private void Searchtab7BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Searchtab7BtnActionPerformed
        // TODO add your handling code here:
        
            
            if(!ah.getAirplaneHistory().isEmpty())
            {
                populateTable4();
            }
            else if(manuTable != null && manuTable.getModel() == null)
            {
                JOptionPane.showMessageDialog(null,"No matches manufacturer now");
            }
            else{JOptionPane.showMessageDialog(null,"No matches manufacturer now");}
    
        
    }//GEN-LAST:event_Searchtab7BtnActionPerformed

    private void updateTimeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateTimeBtnActionPerformed
        // TODO add your handling code here:
        if(ah.getDate()!=null){
            
            timeTxt.setText(String.valueOf(ah.getDate()));
        }
        else
        {
            JOptionPane.showMessageDialog(null,"No update time now");
        }
    }//GEN-LAST:event_updateTimeBtnActionPerformed

    private void iAirportTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iAirportTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iAirportTxtActionPerformed

    private void searchBtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtn6ActionPerformed
        // TODO add your handling code here:
            populateairportTable();
    }//GEN-LAST:event_searchBtn6ActionPerformed

    private void expiredBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expiredBtnActionPerformed
        // TODO add your handling code here:
           populatecertificateTable();
    }//GEN-LAST:event_expiredBtnActionPerformed
     
    public void populatecertificateTable(){
        DefaultTableModel dtm = (DefaultTableModel)certificateTable.getModel();
        dtm.setRowCount(0); 
        
            for(Airplane vs: ah.getAirplaneHistory())
            {
                if("Expired".equals(vs.getCertificate())){
                    Object row[] = new Object[8];
                    row[0] = vs.getSerialNum();
                    row[1] = vs.getModelNum();
                    row[2] = vs.getAirLinerstart() + "to" + vs.getAirLinerstart();
                    row[3] = vs.getAirport();
                    row[4] = vs;
                    row[5] = vs.getSeats(); 
                    row[6] = vs.getYear();
                    row[7] = vs.getStatus();
                    dtm.addRow(row);                
                }
            
            }
    }  
     
    public void populateairportTable(){
        DefaultTableModel dtm = (DefaultTableModel)airportTable.getModel();
        dtm.setRowCount(0); 
        
            for(Airplane vs: ah.getAirplaneHistory())
            {
                if("Available".equals(vs.getStatus()) && iAirportTxt.getText().equals(vs.getAirport())){
                    Object row[] = new Object[8];

                    row[0] = vs.getSerialNum();
                    row[1] = vs.getModelNum();
                    row[2] = vs.getAirLinerstart() + "\t to \t"  + vs.getAirLinerend();
                    row[3] = vs.getAirport();
                    row[4] = vs;
                    row[5] = vs.getSeats(); 
                    row[6] = vs.getYear();
                    row[7] = vs.getStatus();

                    dtm.addRow(row);
                
                }
            
            }
    }  
    public void populateTable1(){
        DefaultTableModel dtm = (DefaultTableModel)yearTable.getModel();
        dtm.setRowCount(0); 
        
            for(Airplane vs: ah.getAirplaneHistory())
            {
                if(tab3yeartxt.getText().equals(String.valueOf(vs.getYear()))){
                    Object row[] = new Object[8];

                    row[0] = vs.getSerialNum();
                    row[1] = vs.getModelNum();
                    row[2] = vs.getAirLinerstart() +"\t to \t"  + vs.getAirLinerend();
                    row[3] = vs.getAirport();
                    row[4] = vs;
                    row[5] = vs.getSeats(); 
                    row[6] = vs.getYear();
                    row[7] = vs.getStatus();

                    dtm.addRow(row);
                
                }
            
            }
    }  
    
    public void populateTable4(){
        DefaultTableModel dtm = (DefaultTableModel)manuTable.getModel();
        dtm.setRowCount(0); 
        
            for(Airplane vs: ah.getAirplaneHistory())
            {
                if(airlinerstartTxt.getText().equals(vs.getAirLinerstart()) && airlinerendTxt.getText().equals(vs.getAirLinerend())){
                   
                    Object row[] = new Object[2];
                    row[0] = vs;
                    row[1] = vs.getSerialNum();
                    dtm.addRow(row);
                
                }
            
            }
    }    
public void populateTable2(int Minseats, int Maxseats){
        DefaultTableModel dtm = (DefaultTableModel)seatsTable.getModel();
        dtm.setRowCount(0); 

         for(Airplane vs: ah.getAirplaneHistory())
            {
                if(Minseats <= vs.getSeats() && vs.getSeats()< Maxseats && "Available".equals(vs.getStatus())){

                    Object row[] = new Object[8];

                    row[0] = vs.getSerialNum();
                    row[1] = vs.getModelNum();
                    row[2] = vs.getAirLinerstart() + "\t to \t"  + vs.getAirLinerend();
                    row[3] = vs.getAirport();
                    row[4] = vs;
                    row[5] = vs.getSeats(); 
                    row[6] = vs.getYear();
                    row[7] = vs.getStatus();
                    dtm.addRow(row);
                    break;
                }
            }
    }    
    
    public static boolean isInt(String s){
        for(int i = 0; i < s.length(); i++){
            if(!Character.isDigit(s.charAt(i))){
                 return false;
            }
        }
        return true;
    }                           

    public void populateTable3(){
        DefaultTableModel dtm = (DefaultTableModel)modelNumTable.getModel();
        dtm.setRowCount(0); 
        
            for(Airplane vs: ah.getAirplaneHistory())
            {
                if(iModelNumTxt.getText().equals(String.valueOf(vs.getModelNum()))){
                    Object row[] = new Object[8];

                    row[0] = vs.getSerialNum();
                    row[1] = vs.getModelNum();
                    row[2] = vs.getAirLinerstart() +"\t to \t"  + vs.getAirLinerend();
                    row[3] = vs.getAirport();
                    row[4] = vs;
                    row[5] = vs.getSeats(); 
                    row[6] = vs.getYear();
                    row[7] = vs.getStatus();

                    dtm.addRow(row);
                
                }
            }
            
        }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnumBtn;
    private javax.swing.JTextField AvaiNumTxt7;
    private javax.swing.JTable BairplaneTable;
    private javax.swing.JPanel Find1jPanel63;
    private javax.swing.JButton FindfBtn;
    private javax.swing.JButton SearchBtn3;
    private javax.swing.JButton Searchtab5Btn;
    private javax.swing.JButton Searchtab6Btn;
    private javax.swing.JButton Searchtab7Btn;
    private javax.swing.JTextField SeatsXtxt;
    private javax.swing.JTextField airlinerTxt;
    private javax.swing.JTextField airlinerTxt1;
    private javax.swing.JTextField airlinerendTxt;
    private javax.swing.JTextField airlinerendTxt1;
    private javax.swing.JTextField airlinerstartTxt;
    private javax.swing.JTable airportTable;
    private javax.swing.JTextField airportTxt;
    private javax.swing.JTextField airportTxt1;
    private javax.swing.JTable certificateTable;
    private javax.swing.JTextField certificateTxt;
    private javax.swing.JButton expiredBtn;
    private javax.swing.JTextField iAirportTxt;
    private javax.swing.JTextField iModelNumTxt;
    private javax.swing.JTextField iSNumTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTable manuTable;
    private javax.swing.JTextField manuTxt;
    private javax.swing.JTextField manuTxt1;
    private javax.swing.JTable modelNumTable;
    private javax.swing.JTextField modelNumTxt;
    private javax.swing.JTextField modelNumTxt1;
    private javax.swing.JButton searchBtn4;
    private javax.swing.JButton searchBtn5;
    private javax.swing.JButton searchBtn6;
    private javax.swing.JTextField seatsNumTxt;
    private javax.swing.JTextField seatsNumTxt1;
    private javax.swing.JTable seatsTable;
    private javax.swing.JTextField seatsYtxt;
    private javax.swing.JTextField serialNumTxt;
    private javax.swing.JTextField serialNumTxt1;
    private javax.swing.JTextField statusTxt;
    private javax.swing.JTextField tab3yeartxt;
    private javax.swing.JTextField timeTxt;
    private javax.swing.JButton updateTimeBtn;
    private javax.swing.JTable yearTable;
    private javax.swing.JTextField yearTxt;
    private javax.swing.JTextField yearTxt1;
    // End of variables declaration//GEN-END:variables
}
