/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.SystemAdminJPanel;

import Business.HumanResources.personDirectory;
import Business.SystemAdministration.UserAccount;
import Business.SystemAdministration.userAccountDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author yiyangyang
 */
public class systemAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form systemAdminWorkAreaJPanel
     */
   
    private JPanel CardSequenceJPanel;
    private userAccountDirectory uad;
    private UserAccount userAccount;
    private personDirectory pd;
    

    


    public systemAdminWorkAreaJPanel(JPanel CardSequenceJPanel, UserAccount userAccount, userAccountDirectory uad, personDirectory pd) {
        initComponents();
        this.CardSequenceJPanel = CardSequenceJPanel;
        this.uad = uad;   
        this.userAccount = userAccount;
        this.pd = pd;
        populateAdminDetails();    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        adminNameTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        adminRoleTxt = new javax.swing.JTextField();
        mngUserAccountbtn = new javax.swing.JButton();
        btnBack2 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("System Admin Work Area");

        jLabel2.setText("Admin Name:");

        adminNameTxt.setEnabled(false);
        adminNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminNameTxtActionPerformed(evt);
            }
        });

        jLabel4.setText("Role:");

        adminRoleTxt.setEnabled(false);
        adminRoleTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminRoleTxtActionPerformed(evt);
            }
        });

        mngUserAccountbtn.setText("Manage user accounts");
        mngUserAccountbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngUserAccountbtnActionPerformed(evt);
            }
        });

        btnBack2.setText("<< Back");
        btnBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mngUserAccountbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(adminRoleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(adminNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnBack2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(207, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnBack2)
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(adminNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(adminRoleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addComponent(mngUserAccountbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void populateAdminDetails(){
        adminNameTxt.setText(userAccount.getUserName());
        adminRoleTxt.setText(userAccount.getRole());
        
    }
    private void adminNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminNameTxtActionPerformed

    private void adminRoleTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminRoleTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminRoleTxtActionPerformed

    private void btnBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack2ActionPerformed
        // TODO add your handling code here:
            CardSequenceJPanel.remove(this);
            CardLayout layout=(CardLayout)CardSequenceJPanel.getLayout();
            layout.previous(CardSequenceJPanel);
    }//GEN-LAST:event_btnBack2ActionPerformed

    private void mngUserAccountbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngUserAccountbtnActionPerformed
        // TODO add your handling code here:
            MnguUserAccountsJPanel panel =new MnguUserAccountsJPanel(CardSequenceJPanel,uad,pd);
            CardSequenceJPanel.add("MnguUserAccountsJPanel",panel);
            CardLayout layout=(CardLayout)CardSequenceJPanel.getLayout();
            layout.next(CardSequenceJPanel);
    }//GEN-LAST:event_mngUserAccountbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adminNameTxt;
    private javax.swing.JTextField adminRoleTxt;
    private javax.swing.JButton btnBack2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton mngUserAccountbtn;
    // End of variables declaration//GEN-END:variables
}
