/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Airliner;
import Business.Airliners;
import Business.Airplane;
import Business.Customer;
import Business.CustomerDirectory;
import Business.Fleet;
import Business.Flight;
import Business.FlightSchedule;
import Business.MasterScheduel;
import Business.Seat;
import Business.TravelAgency;
import UserInterface.Search.SearchFlights;
import UserInterface.manageAirliners.ManageAirlinersJPanel;

import UserInterface.manageCustomer.searchBestFlights;
import java.awt.CardLayout;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;


/**
 *
 * @author yiyangyang
 */
public class TravelAgencyMain extends javax.swing.JFrame {
    private MasterScheduel masterScheduel;
    private Airliners airliners;
    private CustomerDirectory cd;
    private MasterScheduel ms;
    /**
     * Creates new form TravelAgencyMain
     */
      
    public TravelAgencyMain() {
        this.masterScheduel=new MasterScheduel();
        initComponents();
        this.airliners = new Airliners();
	this.cd = new CustomerDirectory();
	this.ms = new MasterScheduel();
        readFile();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        travelAgencyBtn = new javax.swing.JButton();
        mngCustomerBtn = new javax.swing.JButton();
        mngAirliners = new javax.swing.JButton();
        CardSequenceJPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        travelAgencyBtn.setText("Manage Travel Agency");
        travelAgencyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                travelAgencyBtnActionPerformed(evt);
            }
        });

        mngCustomerBtn.setText("Manage Customer");
        mngCustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngCustomerBtnActionPerformed(evt);
            }
        });

        mngAirliners.setText(" Manage Airliners");
        mngAirliners.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngAirlinersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(travelAgencyBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mngCustomerBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mngAirliners, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(travelAgencyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130)
                .addComponent(mngCustomerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138)
                .addComponent(mngAirliners, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        jSplitPane2.setLeftComponent(jPanel1);

        CardSequenceJPanel.setLayout(new java.awt.CardLayout());
        jSplitPane2.setRightComponent(CardSequenceJPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 951, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mngAirlinersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngAirlinersActionPerformed
      
            // TODO add your handling code here:
        ManageAirlinersJPanel panel=new ManageAirlinersJPanel(CardSequenceJPanel,airliners);
        CardSequenceJPanel.add("SearchFlights",panel);
        CardLayout layout=(CardLayout)CardSequenceJPanel.getLayout();
        layout.next(CardSequenceJPanel);
        
    }//GEN-LAST:event_mngAirlinersActionPerformed

    private void travelAgencyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_travelAgencyBtnActionPerformed
        // TODO add your handling code here:
        
       
        SearchFlights panel=new SearchFlights(CardSequenceJPanel,masterScheduel);
        CardSequenceJPanel.add("SearchFlights",panel);
        CardLayout layout=(CardLayout)CardSequenceJPanel.getLayout();
        layout.next(CardSequenceJPanel);
    }//GEN-LAST:event_travelAgencyBtnActionPerformed

    private void mngCustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngCustomerBtnActionPerformed
        // TODO add your handling code here:
        searchBestFlights panel=new searchBestFlights(CardSequenceJPanel,masterScheduel,cd);
        CardSequenceJPanel.add("searchBestFlights",panel);
        CardLayout layout=(CardLayout)CardSequenceJPanel.getLayout();
        layout.next(CardSequenceJPanel);
    }//GEN-LAST:event_mngCustomerBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public void readFile(){
                
		String dir = System.getProperty("user.dir")+"/src"; // get absolute path of current directory
  
		String airlinersFile = dir + "/Business/Airliners.csv";
		String customersFile = dir + "/Business/CustomerDirectory.csv";
		String fleetFile = dir + "/Business/Fleet.csv";
		String fsFile1 = dir + "/Business/FlightSchedule1.csv";
		String comma = ",";
		String line = "";
		String[] strs;

		try {
			BufferedReader airlinersBr = new BufferedReader(new FileReader(airlinersFile));
			BufferedReader customersBr = new BufferedReader(new FileReader(customersFile));
			BufferedReader fleetBr = new BufferedReader(new FileReader(fleetFile));
			BufferedReader fsBr = new BufferedReader(new FileReader(fsFile1));
			
			while ((line = airlinersBr.readLine()) != null) {
				strs = line.split(comma);
				String airlinerID = strs[0];
				String name = strs[1];
				String year = strs[2];
                                String website = strs[3];
				Fleet fleet = new Fleet();				
				Airliner airliner = airliners.addAirliner();
				airliner.setId(airlinerID);
				airliner.setNameOfcompany(name);
				airliner.setYear(year);
				airliner.setFleet(fleet);
                                airliner.setWebsite(website);
				fleetBr = new BufferedReader(new FileReader(fleetFile));
				while ((line = fleetBr.readLine()) != null) {
					strs = line.split(comma);
					String airplaneYear = strs[1];
					String airplaneStatus = strs[2];
					String serialNum = strs[3];
					String seatsCount = strs[4];
					String modalNum = strs[5];
					String manufacturer = strs[6];
					String certificate = strs[7];
					String airport = strs[8];
					String airlinerstart= strs[9];
					String airlinerName = strs[10];
					if (airlinerName.toLowerCase().equals(name.toLowerCase())) {
						 Airplane airplane = fleet.addAirplane();
						 airplane.setYear(Integer.valueOf(airplaneYear));
						 airplane.setStatus(airplaneStatus);
						 airplane.setSerialNum(Integer.valueOf(serialNum));
						 airplane.setSeats(Integer.valueOf(seatsCount));
						 airplane.setModelNum(Integer.valueOf(modalNum));
						 airplane.setManufacturer(manufacturer);
						 airplane.setCertificate(certificate);
						 airplane.setAirport(airport);
						 airplane.setAirLinerstart(airlinerstart);
						 airplane.setAirliner(airliner);
					}
				}
			}
			fleetBr.close();
			airlinersBr.close();
			

			//MasterScheduel masterScheduel = new MasterScheduel();
			//CustomerDirectory customerDirectory = new CustomerDirectory();

			for (int i = 0; i < airliners.getAirliners().size(); i++) {
				
				FlightSchedule flightSchedule = masterScheduel.addFlightS();
				Airliner theairliner = airliners.getAirliners().get(i);
				theairliner.setFlightSchedule(flightSchedule);

				fsBr = new BufferedReader(new FileReader(fsFile1));
				while ((line = fsBr.readLine()) != null) {
					strs = line.split(comma);
					String flightid = strs[0];
					String departure= strs[1];
					String destination = strs[2];
					String airplaneID = strs[3];
					String airlinerIDflight = strs[4];
                                        String flightDate = strs[5];
                                        
                                        String Pday = strs[6];
					
					if (airlinerIDflight.equals(theairliner.getId())) {
						Flight flight = flightSchedule.addFlight();
						flight.setId(flightid);
						flight.setDeparture(departure);
						flight.setDestination(destination);
						flight.setAirliner(theairliner);
                                                flight.setPreferedDay(Pday);
                                                flight.setDate(flightDate);
						
						if (theairliner.getFleet().getFleet().size() > 0) {
							flight.setAirplane(theairliner.getFleet().getFleet().get(Integer.valueOf(airplaneID)));
						} else {
							flight.setAirplane(new Airplane());
						}
						
						// seats assignment
						Seat[][] seats = new Seat[25][6];
						flight.setSeats(seats);
	
						customersBr = new BufferedReader(new FileReader(customersFile));
						while ((line = customersBr.readLine()) != null) {
							strs = line.split(comma);
							String flightID = strs[4];
	
							if (flightID.equals(flightid)) {
								String cusName = strs[1];
								int cusAge = Integer.valueOf(strs[2]);
								String[] cusSeat = strs[3].split("_");
								int row = Integer.valueOf(cusSeat[0]) - 1;
								int col = Integer.valueOf(cusSeat[1]) - 1;
                                                                int id = Integer.valueOf(strs[0]) - 1;
								Customer customer= cd.addCustomer();
								customer.setAge(cusAge);
								customer.setName(cusName);
                                                                customer.setId(id);
                                                                customer.setFlightID(Integer.parseInt(flightID));
								Seat seat = new Seat();
								seat.setCustomer(customer);
								seat.setRow(row);
								seat.setCol(col);
								seat.setPrice(); // set seat price according to the position
								customer.setSeat(seat);
																
								seats[row][col] = seat;
							}
						}
					}
				
				}
			}
			fsBr.close();
			customersBr.close();
			
		} catch (IOException e) {
			e.printStackTrace();
		}
                
                TravelAgency ta = new TravelAgency(airliners, cd, ms);
                int totalOfALLairliner = 0;
                for (Airliner airliner : ta.getAirliners().getAirliners()) {
			// print it
			 totalOfALLairliner += airliner.getFlightSchedule().getSumOfPrice();
                         
		}
		System.out.println("sum of price pf all airliner :\t" + totalOfALLairliner);
                
		for (Airliner airliner : ta.getAirliners().getAirliners()) {
			// print it
			int totalOfpairliner = airliner.getFlightSchedule().getSumOfPrice();
			System.out.println("sum of price per airliner " + airliner.getNameOfcompany() + ":\t" + totalOfpairliner);
		}
                
                for (Airliner airliner : ta.getAirliners().getAirliners()) {
                    
                        for(Flight flight : airliner.getFlightSchedule().getFlightSchedule()){
                            int totalOfpFlight = flight.getSumOfPrice();
                        
                            System.out.println("sum of price per flight using airplane "+ flight.getAirplane().getSerialNum() + " airliner " + airliner.getNameOfcompany() + "\t:" + totalOfpFlight);
                        }
                }                
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TravelAgencyMain().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CardSequenceJPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JButton mngAirliners;
    private javax.swing.JButton mngCustomerBtn;
    private javax.swing.JButton travelAgencyBtn;
    // End of variables declaration//GEN-END:variables
}
